services:
  mongo:
    image: mongo
    ports:
      - '27017:27017'
    volumes:
      - mongo-data:/data/db
    networks:
      - my-network

  auth-service:
    build:
      context: ./auth-service
    ports:
      - '3000:3000'
    env_file:
      - ./auth-service/.env
    depends_on:
      - mongo
    networks:
      - my-network

  profile-service:
    build:
      context: ./profile-service
    ports:
      - '3002:3001'
    env_file:
      - ./profile-service/.env
    depends_on:
      - mongo
    volumes:
    - ./profile-service/uploads:/app/uploads

    networks:
      - my-network

  post-service:
    build:
      context: ./post-service
    ports:
      - '3003:3003'
    env_file:
      - ./post-service/.env
    depends_on:
      - mongo
    networks:
      - my-network
  

  client:
    build:
      context: ./client
    ports:
      - '3001:3000'
    depends_on:
      - auth-service
    networks:
      - my-network

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - '8080:8080'
    depends_on:
      - auth-service
      - client
    networks:
      - my-network

volumes:
  mongo-data:

networks:
  my-network:
    driver: bridge
